#!/usr/bin/env python3
"""Generate pinned Unicode 17 grapheme/width tables and unchanged conformance cases."""
from pathlib import Path
import hashlib,json
root=Path(__file__).resolve().parents[2];data=Path(__file__).resolve().parent
for name,entry in json.loads((data/'sources.json').read_text()).items():
 assert hashlib.sha256((data/name).read_bytes()).hexdigest()==entry['sha256'],name
props={'CR':1,'LF':2,'Control':3,'Extend':4,'ZWJ':5,'Regional_Indicator':6,'Prepend':7,'SpacingMark':8,'L':9,'V':10,'T':11}
def ranges(file,field,values):
 rows=[]
 for line in (data/file).read_text().splitlines():
  bits=[v.strip() for v in line.split('#')[0].split(';')]
  if len(bits)<=field or bits[field] not in values:continue
  if file=='DerivedCoreProperties.txt' and bits[1]!='InCB':continue
  ends=bits[0].split('..');rows.append([int(ends[0],16),int(ends[-1],16),values[bits[field]]])
 result=[]
 for a,b,v in sorted(rows):
  if result and result[-1][1]+1==a and result[-1][2]==v:result[-1][1]=b
  else:result.append([a,b,v])
 return result
sets={'breaks':ranges('GraphemeBreakProperty.txt',1,props),'indic':ranges('DerivedCoreProperties.txt',2,{'Consonant':1,'Extend':2,'Linker':3}),'pictographic':ranges('emoji-data.txt',1,{'Extended_Pictographic':1})}
s='''package build.raft.mermaid.core

// Generated by compatibility/unicode-17/generate.py; do not edit.
// Unicode 17.0 data, Copyright Unicode, Inc. Unicode License v3; see NOTICE.
internal object UnicodeGraphemeData {
'''
for name,rows in sets.items():
 vals=[str(v) for row in rows for v in row];s+=f'    val {name}: IntArray = intArrayOf(\n'
 for i in range(0,len(vals),12):s+='        '+', '.join(vals[i:i+12])+',\n'
 s+='    )\n'
s+='}\n';(root/'mermaid-core/src/commonMain/kotlin/build/raft/mermaid/core/UnicodeGraphemeData.kt').write_text(s)
cases=[]
for line in (data/'GraphemeBreakTest.txt').read_text().splitlines():
 body=line.split('#')[0].strip()
 if body:cases.append(body)
# Chunk literals below JVM constant-pool and method limits.
chunks=['\n'.join(cases[i:i+80]) for i in range(0,len(cases),80)]
s='''package build.raft.mermaid.core

// Unchanged boundary tokens from Unicode 17.0 GraphemeBreakTest.txt.
// Unicode License v3; generated by compatibility/unicode-17/generate.py.
internal val unicodeGraphemeCases: List<String> = listOf(
'''+''.join('    """'+c+'""",\n' for c in chunks)+')\n'
(root/'mermaid-core/src/commonTest/kotlin/build/raft/mermaid/core/UnicodeGraphemeCases.kt').write_text(s)
print({k:len(v) for k,v in sets.items()},'conformance cases',len(cases))

# Only BMP W/F characters need correction: supplementary UTF-16 pairs already
# reserve 1.2 em in the fallback measurer. Keep their historical metrics intact.
wide = [(a, min(b, 0xFFFF)) for a, b, _ in ranges('EastAsianWidth.txt', 1, {'W': 1, 'F': 1}) if a <= 0xFFFF]
s = '''package build.raft.mermaid.layout.simple

// Generated by compatibility/unicode-17/generate.py; do not edit.
// Unicode 17.0 EastAsianWidth W/F BMP ranges. Unicode License v3; see NOTICE.
internal object UnicodeWideBmpData {
    private val ranges: IntArray = intArrayOf(
'''
values = [str(v) for row in wide for v in row]
for i in range(0, len(values), 12):
 s += '        ' + ', '.join(values[i:i+12]) + ',\n'
s += '''    )

    fun contains(code: Int): Boolean {
        var low = 0
        var high = ranges.size / 2 - 1
        while (low <= high) {
            val mid = (low + high) / 2
            when {
                code < ranges[mid * 2] -> high = mid - 1
                code > ranges[mid * 2 + 1] -> low = mid + 1
                else -> return true
            }
        }
        return false
    }
}
'''
(root/'mermaid-layout-simple/src/commonMain/kotlin/build/raft/mermaid/layout/simple/UnicodeWideBmpData.kt').write_text(s)
print('wide/fullwidth BMP ranges', len(wide))

# Recognize only Unicode-listed multi-codepoint emoji forms. A grapheme alone
# does not imply one glyph (e.g. arbitrary pictographic ZWJ combinations).
emoji = []
for line in (data/'emoji-test.txt').read_text().splitlines():
 body=line.split('#')[0].strip()
 if not body: continue
 points,status=map(str.strip,body.split(';'))
 codes=points.split()
 if len(codes)>1 and status in {'fully-qualified','minimally-qualified','unqualified'}:
  emoji.append(''.join(chr(int(code,16)) for code in codes))
emoji=sorted(set(emoji))
chunks=['\n'.join(emoji[i:i+80]) for i in range(0,len(emoji),80)]
s='''package build.raft.mermaid.layout.simple

// Generated by compatibility/unicode-17/generate.py; do not edit.
// Unicode 17.0 emoji-test multi-codepoint forms; Unicode License v3, see NOTICE.
internal object UnicodeEmojiSequences {
    private val sequences: Set<String> = listOf(
'''+''.join('        """'+chunk+'""",\n' for chunk in chunks)+'''    ).flatMap { it.lines() }.toSet()

    fun contains(cluster: String): Boolean = cluster in sequences
}
'''
(root/'mermaid-layout-simple/src/commonMain/kotlin/build/raft/mermaid/layout/simple/UnicodeEmojiSequences.kt').write_text(s)
print('multi-codepoint emoji sequences',len(emoji))
