#!/usr/bin/env python3
"""Replay unchanged Architecture model assertions against the production Native Architecture parser and model."""
import argparse,base64,hashlib,json,os,shutil,subprocess
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--upstream',type=Path,required=True);p.add_argument('--repo',type=Path,default=Path(__file__).resolve().parents[2]);p.add_argument('--stdlib',type=Path,required=True);o=p.parse_args()
u=o.upstream.resolve();r=o.repo.resolve();h=Path(__file__).resolve().parent;w=u/'.native-architecture-model-audit';w.mkdir(exist_ok=True)
m=json.loads((h/'sources.json').read_text())
for f,sha in m['files'].items():assert hashlib.sha256((u/f).read_bytes()).hexdigest()==sha,f
jar=w/'native-runtime.jar';shutil.copy2(r/'mermaid-core/build/intermediates/runtime_library_classes_jar/debug/bundleLibRuntimeToJarDebug/classes.jar',jar)
cp=os.pathsep.join(map(str,[w,jar,o.stdlib.resolve(),r/'mermaid-layout-simple/build/intermediates/runtime_library_classes_jar/debug/bundleLibRuntimeToJarDebug/classes.jar',r/'mermaid-layout-api/build/intermediates/runtime_library_classes_jar/debug/bundleLibRuntimeToJarDebug/classes.jar']));subprocess.run(['javac','-cp',cp,'-d',str(w),str(h/'ArchitectureModelNativeBridge.java')],check=True)
calls=w/'official-calls.jsonl';calls.write_text('')
(w/'capture.ts').write_text("import {vi,expect} from 'vitest';\nimport {ArchitectureDB} from '../packages/mermaid/src/diagrams/architecture/architectureDb.js';\nimport {parser} from '../packages/mermaid/src/diagrams/architecture/architectureParser.js';\nconst sources=new WeakMap();\nfunction append(db,method,value){\n const lines=sources.get(db)||['architecture-beta'];\n let line='';\n if(method==='addLayoutHint')line='align '+value.direction+' '+value.members.join(' ');\n else {const kind={addGroup:'group',addService:'service',addJunction:'junction'}[method];line=kind+' '+value.id;if(kind!=='junction'){if(value.icon)line+='('+value.icon+')';if(value.title)line+='['+JSON.stringify(value.title)+']';}if(value.in)line+=' in '+value.in;}\n return [...lines,line];\n}\nimport {appendFileSync} from 'node:fs';\nlet parsing=false;\nconst clear=ArchitectureDB.prototype.clear;\nvi.spyOn(ArchitectureDB.prototype,'clear').mockImplementation(function(){sources.set(this,['architecture-beta']);return clear.call(this);});\nconst parse=parser.parse;\nvi.spyOn(parser,'parse').mockImplementation(async source=>{appendFileSync(CALLS,JSON.stringify({test:expect.getState().currentTestName,source})+'\\n');parsing=true;try{return await parse(source);}finally{parsing=false;}});\nfor(const method of ['addGroup','addService','addJunction','addLayoutHint']){\n const original=ArchitectureDB.prototype[method];vi.spyOn(ArchitectureDB.prototype,method).mockImplementation(function(value){\n  if(parsing)return original.call(this,value);\n  const lines=append(this,method,value);appendFileSync(CALLS,JSON.stringify({test:expect.getState().currentTestName,source:lines.join('\\n')})+'\\n');\n  const result=original.call(this,value);sources.set(this,lines);return result;\n });\n}\n".replace('CALLS',json.dumps(str(calls))))
config="""import {defineConfig} from 'vitest/config';
import jsonSchemaPlugin from '../.vite/jsonSchemaPlugin.js';
import ts from 'typescript';
import {resolve} from 'node:path';
export default defineConfig({plugins:[{name:'original-typescript-target',enforce:'pre',transform(code,id){if(id.endsWith('/architecture.spec.ts'))return {code:ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2018,module:ts.ModuleKind.ESNext}}).outputText,map:null};}},jsonSchemaPlugin()],resolve:{alias:{'@mermaid-js/parser':resolve('packages/parser/src/index.ts')}},define:{'injected.includeLargeFeatures':'true','injected.profiling':'false',packageVersion:"'0.0.0'"},test:{environment:'jsdom',globals:true,maxWorkers:1,testTimeout:30000,include:FILES,setupFiles:['.native-architecture-model-audit/SETUP.ts']}});
""".replace('FILES',json.dumps(list(m['files'])))
for mode,setup in [('official','capture'),('native','adapter')]:
 (w/f'{mode}.config.ts').write_text(config.replace('SETUP',setup));(w/f'{mode}.workspace.ts').write_text("import {defineWorkspace} from 'vitest/config';export default defineWorkspace(['.native-architecture-model-audit/"+mode+".config.ts']);")
def test(mode):
 with (w/f'{mode}.log').open('w') as f:return subprocess.run(['pnpm','exec','vitest','run','--config',f'.native-architecture-model-audit/{mode}.config.ts','--workspace',f'.native-architecture-model-audit/{mode}.workspace.ts', '--testNamePattern',"^(?!.*(?:cytoscape stylesheet|fcose layout config|randomize config|block proto pollution via service id)).*$",'--reporter=json',f'--outputFile={w/(mode+".json")}'],cwd=u,env={**os.environ,'TZ':'UTC'},stdout=f,stderr=subprocess.STDOUT,timeout=240)
if test('official').returncode:raise SystemExit('Original Architecture model suite failed')
assert json.loads((w/'official.json').read_text())['numPassedTests']==25, 'Expected exactly 25 selected original Architecture assertions'
sources=list(dict.fromkeys(json.loads(x)['source'] for x in calls.read_text().splitlines()))
result=subprocess.run(['java','-cp',cp,'ArchitectureModelNativeBridge'],input=''.join(base64.b64encode(s.encode()).decode()+'\n' for s in sources),text=True,capture_output=True,check=True,timeout=60)
models=[json.loads(x) for x in result.stdout.splitlines()];assert len(models)==len(sources)
cache=w/'native-models.json';cache.write_text(json.dumps(list(zip(sources,models))))
(w/'adapter.ts').write_text("import {vi,expect} from 'vitest';\nimport {ArchitectureDB} from '../packages/mermaid/src/diagrams/architecture/architectureDb.js';\nimport {parser} from '../packages/mermaid/src/diagrams/architecture/architectureParser.js';\nconst sources=new WeakMap();\nfunction append(db,method,value){\n const lines=sources.get(db)||['architecture-beta'];\n let line='';\n if(method==='addLayoutHint')line='align '+value.direction+' '+value.members.join(' ');\n else {const kind={addGroup:'group',addService:'service',addJunction:'junction'}[method];line=kind+' '+value.id;if(kind!=='junction'){if(value.icon)line+='('+value.icon+')';if(value.title)line+='['+JSON.stringify(value.title)+']';}if(value.in)line+=' in '+value.in;}\n return [...lines,line];\n}\nimport {readFileSync} from 'node:fs';\nconst models=new Map(JSON.parse(readFileSync(CACHE,'utf8')));\nconst state=new WeakMap();\nfunction lookup(source){const result=models.get(source);if(!result)throw new Error('Missing Native model');if(result.error)throw new Error(result.error);return structuredClone(result);}\nfunction attach(db,model){state.set(db,model);for(const getter of ['getDiagramTitle','getAccTitle','getAccDescription'])db[getter]=()=>state.get(db)?.[getter]??'';}\nconst clear=ArchitectureDB.prototype.clear;\nvi.spyOn(ArchitectureDB.prototype,'clear').mockImplementation(function(){clear.call(this);sources.set(this,['architecture-beta']);attach(this,{});});\nvi.spyOn(parser,'parse').mockImplementation(async source=>{const db=parser.parser.yy;attach(db,lookup(source));sources.set(db,source.split('\\n'));});\nfor(const method of ['addGroup','addService','addJunction','addLayoutHint'])vi.spyOn(ArchitectureDB.prototype,method).mockImplementation(function(value){const lines=append(this,method,value);const result=lookup(lines.join('\\n'));sources.set(this,lines);attach(this,result);});\nfor(const getter of ['getServices','getGroups','getJunctions','getLayoutHints'])vi.spyOn(ArchitectureDB.prototype,getter).mockImplementation(function(){return state.get(this)?.[getter]??[];});\n".replace('CACHE',json.dumps(str(cache))))
status=test('native');summary={'upstreamRevision':m['revision'],'nativeJarSha256':hashlib.sha256(jar.read_bytes()).hexdigest(),'uniqueInputs':len(sources),'timezone':'UTC'}
for mode in ['official','native']:
 d=json.loads((w/f'{mode}.json').read_text());summary[mode]={k:d[k] for k in ['numTotalTests','numPassedTests','numFailedTests','numPendingTests','success']}
(w/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(summary,indent=2));raise SystemExit(status.returncode)
